# Generated by Django 2.1 on 2018-08-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTruck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
